[package]
name = "dns-agent"
version = "0.1.0"
authors = ["Clément Nivolle <clement@nivolle.com>"]

[dependencies]
trust-dns-resolver = "0.6.0"
warp10 = "0.8.1"
log = "0.3.8"
env_logger = "0.4.3"
time = "0.1.38"